Prometeus/urls.py
# -*- coding: utf-8 -*-

# Django's Libraries
from django.conf import settings
from django.conf.urls import url
from django.conf.urls import include
from django.conf.urls.static import static

from django.contrib import admin


urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^admin/', admin.site.urls),

    url(r'', include('editorial.urls', namespace="editorial")),
    url(r'', include('home.urls', namespace="home")),
    url(r'', include('labor.urls', namespace="labor")),
    url(r'', include('management.urls', namespace="management")),
    url(r'', include('payroll.urls', namespace="payroll")),
    url(r'', include('security.urls', namespace="security")),

    url(r'api/', include('payroll.urls_rest', namespace="api-payroll")),
    url(r'api/', include('social.urls_rest', namespace="api-social")),
    url(r'api/', include('labor.urls_rest', namespace="api-labor")),
]


if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

editorial/urls.py
# -*- coding: utf-8 -*-

# Django's Libraries
from django.conf.urls import url

# Own's Libraries
from .views import PostList
from .views import PostAdd
from .views import PostEdit
from .views import PostView


urlpatterns = [
    url(r'^post/$', PostList.as_view(), name="post_list"),
    url(r'^post/add/$', PostAdd.as_view(), name="post_add"),
    url(r'^post/(?P<_pk>\d+)/edit/$', PostEdit.as_view(), name="post_edit"),
    url(r'^post/(?P<_pk>\d+)/view/$', PostView.as_view(), name="post_view"),
]

home/urls.py
# -*- coding: utf-8 -*-

# Django's Libraries
from django.conf.urls import url

# Own's Libraries
from .views import LandingView


urlpatterns = [
    url(r'^$', LandingView.as_view(), name="landing"),
]

editorial/models.py
# -*- coding: utf-8 -*-

# Python's Libraries
from __future__ import unicode_literals

# Django's Libraries
from django.db import models

# Third-party Libraries
from django_resized import ResizedImageField

# Own's Libraries
from .utilities import Helper
from security.models import Profile


class Post(models.Model):

    STATUS = (
        ('PUB', 'PUBLICADO'),
        ('EDT', 'Editando'),
    )

    title = models.CharField("Titulo", max_length=120)
    image = ResizedImageField(
        "Imagen",
        upload_to=Helper.get_ImagePath_Post,
        quality=75,
        blank=True,
        validators=[
            Helper.validate_Img_Extension,
            Helper.validate_Size
        ]
    )
    content = models.TextField("Contenido", blank=True)

    status = models.CharField(
        "Estado",
        max_length=3,
        choices=STATUS,
        default="EDT"
    )
    created_by = models.ForeignKey(
        Profile,
        verbose_name="Creado por",
        related_name='post_created_by',
        null=True
    )
    created_date = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated_by = models.ForeignKey(
        Profile,
        verbose_name="Actualizado por",
        related_name='post_updated_by',
        null=True
    )
    updated_date = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Pubicación'
        verbose_name_plural = 'Publicaciones'

editorial/forms.py
# -*- coding: utf-8 -*-

# Django's Libraries
from django.forms import ModelForm


from django.forms import Select
from django.forms import TextInput
from django.forms import Textarea
from django.forms import ClearableFileInput

# Own's Libraries
from .models import Post


class PostAddForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(PostAddForm, self).__init__(*args, **kwargs)
        self.fields['title'].required = True
        self.fields['image'].required = True

    class Meta:
        model = Post
        fields = (
            'title',
            'image',
            'content',
        )

        widgets = {
            'title': TextInput(attrs={'class': 'form-control'}),
            'image': ClearableFileInput(attrs={
                'class': 'filestyle',
                'data-buttonText': "Seleccionar Imagen",
                'data-iconName': "glyphicon glyphicon-picture"
            }),
            'content': Textarea(attrs={'class': 'form-control', 'rows': '8'}),
        }

        labels = {
            'title': 'Titulo de la publicacion',
            'image': 'Portada',
            'content': 'Contenido',
        }


class PostEditForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(PostEditForm, self).__init__(*args, **kwargs)
        self.fields['title'].required = True
        self.fields['image'].required = True

    class Meta:
        model = Post
        fields = (
            'title',
            'image',
            'content',
            'status',
        )

        widgets = {
            'title': TextInput(attrs={'class': 'form-control'}),
            'image': ClearableFileInput(attrs={
                'class': 'filestyle',
                'data-buttonText': "Seleccionar Imagen",
                'data-iconName': "glyphicon glyphicon-picture"
            }),
            'content': Textarea(attrs={'class': 'form-control', 'rows': '8'}),
            'status': Select(attrs={'class': 'form-control'}),
        }

        labels = {
            'title': 'Titulo de la publicacion',
            'image': 'Portada',
            'content': 'Contenido',
            'status': 'Estado',
        }

editorial/views.py
# -*- coding: utf-8 -*-

# Python's Libraries
from __future__ import unicode_literals

# Django's Libraries
from django.views.generic.base import View
from django.core.urlresolvers import reverse
from django.contrib import messages

from django.shortcuts import render
from django.shortcuts import redirect

# Own's Libraries
from security.mixins import GroupLoginRequiredMixin
from .business import PostBusiness

from .forms import PostAddForm
from .forms import PostEditForm


class PostList(GroupLoginRequiredMixin, View):
    template_name = 'post/list.html'
    group = ['NOTICIAS_ADM', ]

    def get(self, _request):
        query = _request.GET.get('q')
        posts = PostBusiness.get_FilterBy(query)
        posts_paginated = PostBusiness.get_Paginated(
            posts,
            _request.GET.get('page')
        )

        context = {
            'records': posts_paginated
        }

        return render(_request, self.template_name, context)


class PostAdd(GroupLoginRequiredMixin, View):
    template_name = 'post/add.html'
    group = ['NOTICIAS_ADM', ]

    def get(self, _request):
        form = PostAddForm()
        context = {
            'form': form
        }
        return render(_request, self.template_name, context)

    def post(self, _request):
        form = PostAddForm(_request.POST, _request.FILES)

        if form.is_valid():
            post = form.save(commit=False)

            post.created_by = _request.user.profile
            post.updated_by = _request.user.profile

            post.save()

            return redirect(
                reverse('editorial:post_edit', kwargs={'_pk': post.pk})
            )

        context = {
            'form': form
        }
        return render(_request, self.template_name, context)


class PostEdit(GroupLoginRequiredMixin, View):

    template_name = 'post/edit.html'
    group = ['NOTICIAS_ADM', ]

    def get(self, _request, _pk):

        form = PostEditForm(
            instance=PostBusiness.get(_pk)
        )

        context = {
            'form': form
        }

        return render(_request, self.template_name, context)

    def post(self, _request, _pk):

        form = PostEditForm(
            _request.POST,
            _request.FILES,
            instance=PostBusiness.get(_pk)
        )

        if form.is_valid():
            post = form.save(commit=False)
            post.updated_by = _request.user.profile
            post.save()

            messages.success(
                _request,
                "La Noticia fue actualizada correctamente"
            )

        context = {
            'form': form
        }
        return render(_request, self.template_name, context)


class PostView(View):

    template_name = 'post/view.html'

    def get(self, _request, _pk):
        post = PostBusiness.get(_pk)
        last_post = PostBusiness.get_Last(post)

        context = {
            'record': post,
            'other_records': last_post
        }

        return render(_request, self.template_name, context)

editorial/templates/post/add.html
{% extends 'master_in.html' %}
{% load static from staticfiles %}
{% load forms %}
{% load feedback %}
{% block title %} GCM - Nuevo Noticia {% endblock title %}

{% block css %}

    <!-- Summernote -->
    <link rel="stylesheet" type="text/css" href="{% static 'libs/summernote/0.8.3/summernote.css' %}"/>

    <!-- Own's Styles -->
    <link rel="stylesheet" type="text/css" href="{% static 'tags/components.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'tags/forms.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'tags/image.min.css' %}"/>

{% endblock css %}

{% block content %}

    <div class="container">
        <div class="row">

            <div class="col-xs-12">
                <header>
                    <h3>
                        <ol class="breadcrumb own-breadcrumb">
                            <li class="own-breadcrumb-init">
                                <a href="{% url 'editorial:post_list' %}">Noticias</a>
                            </li>
                          <li>Crear Noticia</li>
                        </ol>
                    </h3>
                </header>
                <hr>
            </div>

            <div class="col-xs-12">
                <div class="own-form-title">
                    Proporciona los siguientes datos:
                </div>

                <form action=""
                method="post"
                class="well"
                enctype="multipart/form-data"> {% csrf_token %}

                    {% tag_messages messages %}

                    {% tag_form_errors form %}

                    {% tag_field form.title %}

                    {% tag_image_nopreview form.image %}

                    {% tag_field form.content %}

                    <div class="text-center">
                        <a href="{% url 'editorial:post_list' %}" class="btn btn-default">Cancelar</a>
                        <button type="submit" class="btn btn-success">
                            <span class="glyphicon glyphicon-ok"></span>
                            Crear noticia
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock content %}

{% block scripts %}

    <!-- Bootstrap Filestyle -->
    <script type="text/javascript" src="{% static 'libs/bootstrap-filestyle/1.2.1/src/bootstrap-filestyle.min.js' %}"></script>

    <!-- Summernote -->
    <script type="text/javascript" src="{% static 'libs/summernote/0.8.3/summernote.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'libs/summernote/0.8.3/lang/summernote-es-ES.js' %}"></script>

    <!-- Own's Scripts -->
    <script type="text/javascript" src="{% static 'post/add.min.js' %}"></script>

{% endblock scripts %}

editorial/templates/post/edit.html
{% extends 'master_in.html' %}
{% load static from staticfiles %}
{% load forms %}
{% load feedback %}

{% block title %} GCM - Editar Noticia {% endblock title %}

{% block css %}

    <!-- Summernote -->
    <link rel="stylesheet" type="text/css" href="{% static 'libs/summernote/0.8.3/summernote.css' %}"/>

    <!-- Own's Styles -->
    <link rel="stylesheet" type="text/css" href="{% static 'tags/components.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'tags/links.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'tags/image.min.css' %}"/>

{% endblock css %}

{% block content %}

    <div class="container ">
        <div class="row">
            <div class="col-xs-12">
                <header>
                    <h3>
                        <ol class="breadcrumb own-breadcrumb">
                          <li class="own-breadcrumb-init"><a href="{% url 'editorial:post_list' %}">Noticias</a></li>
                          <li>{{ form.instance.title }}</li>
                        </ol>
                    </h3>
                </header>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9">

                <form class="" action="" method="post" enctype="multipart/form-data"> {% csrf_token %}

                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">Informacion de la Noticia</h3>
                        </div>
                        <div class="panel-body">

                            {% tag_messages messages %}

                            {% tag_form_errors form %}

                            {% tag_field form.title %}

                            {% tag_image_nopreview form.image %}

                            {% tag_field form.content %}

                            {% tag_field form.status %}

                        </div>
                        <div class="panel-footer text-center">
                            <button type="submit" class="btn btn-success">
                                <span class="glyphicon glyphicon-ok"></span>
                                Guardar
                            </button>
                        </div>
                    </div>

                </form>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                <div class="panel panel-default affix-top">
                    <div class="panel-heading">
                        <h3 class="panel-title">Otras Acciones:</h3>
                    </div>
                    <ul class="list-group">
                        <a class="list-group-item own-link-item text-center" href="{% url 'editorial:post_view' form.instance.pk %}">
                            <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                            Ir a Preview
                        </a>
                    </ul>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

{% block scripts %}

    <!-- Bootstrap Filestyle -->
    <script type="text/javascript" src="{% static 'libs/bootstrap-filestyle/1.2.1/src/bootstrap-filestyle.min.js' %}"></script>

    <!-- Summernote -->
    <script type="text/javascript" src="{% static 'libs/summernote/0.8.3/summernote.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'libs/summernote/0.8.3/lang/summernote-es-ES.js' %}"></script>

    <!-- Own's Scripts -->
    <script type="text/javascript" src="{% static 'post/edit.min.js' %}"></script>

{% endblock scripts %}

editorial/templates/post/list.html
{% extends 'master_in.html' %}

{% load static from staticfiles %}

{% block title %} GCM - Noticias {% endblock title %}

{% block css %}

    <!-- Own's Styles -->
    <link rel="stylesheet" type="text/css" href="{% static 'tags/colors.min.css' %}"/>

{% endblock css %}

{% block content %}

    <div class="container">
        <header>
            <h3 class="own-titulo">Administrar Noticias</h3>
        </header>
        <hr>
        <nav>
            <div class="row">
                <div class="col-xs-12 col-sm-6">
                    <a href="{% url 'editorial:post_add' %}" class="btn btn-primary visible-xs visible-sm-inline visible-md-inline visible-lg-inline">
                        <i class="fa fa-plus-circle" aria-hidden="true"></i>
                        Agregar Noticia
                    </a>
                </div>
                <br class="visible-xs">
                <br class="visible-xs">
                <form class="col-xs-12 col-sm-6" action="" method="get">
                    <div class="input-group">
                        <input type="text" class="form-control" name="q" placeholder="escribe texto a buscar" value="{{ request.GET.q }}">

                        <span class="input-group-btn">
                          <button type="submit" id="boton_buscar" class="btn btn-info btn-flat">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                            <span class="hidden-xs">Buscar</span>
                          </button>
                        </span>
                    </div>
                </form>
            </div>
        </nav>
        <br>
        {% if records %}

            <article>
                <div class="list-group">
                    {% for record in records %}
                        <a href="{% url 'editorial:post_edit' record.pk %}" class="list-group-item">
                            <span class="badge own-color {% if record.status == 'EDT' %} own-color-warning {% else %} own-color-success {% endif %}">
                                <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
                                <span class="hidden-xs">{{ record.get_status_display }}</span>
                            </span>
                            {{ record.title }}
                        </a>
                    {% endfor %}
                </div>
            </article>

            <div class="text-center">
                <ul class="pagination pagination-sm no-margin">
                    {% if users.has_previous %}
                        <li><a href="?{{ page_request_var }}={{ users.previous_page_number }}&q={{ request.GET.q }}">&laquo;</a></li>
                    {% endif %}

                    {% for i in users.paginator.page_range %}
                        <li {% if users.number == i %} class="active own-active" {% endif %}>
                            <a href="?page={{i}}&q={{ request.GET.q }}">{{ i }}</a>
                        </li>
                    {% endfor %}

                    {% if users.has_next %}
                        <li><a href="?page={{ users.next_page_number }}&q={{ request.GET.q }}">&raquo;</a></li>
                    {% endif %}
                </ul>
            </div>

        {% else %}
            <h1 class="text-center">Sin noticias</h1>
        {% endif %}
    </div>

{% endblock content %}

editorial/templates/post/view.html
{% extends 'master_in.html' %}
{% load static from staticfiles %}
{% load forms %}
{% load security %}
{% load humanize %}

{% block title %} GCM - Noticia {% endblock title %}

{% block css %}

    <!-- Own's Styles -->
    <link rel="stylesheet" type="text/css" href="{% static 'post/view.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'tags/links.min.css' %}"/>

{% endblock css %}

{% block content %}

    <div class="container ">

        <div class="row">
            <div class="col-xs-12">
                <header>
                    <h3>
                        <ol class="breadcrumb own-breadcrumb">
                            <li class="own-breadcrumb-init">
                                <a href="{% url 'security:index' %}">
                                    <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
                                    Inicio
                                </a>
                            </li>
                            <li> {{ record.title }} </li>
                        </ol>
                    </h3>
                </header>
            </div>
        </div>

        <div class="row">

            <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9" id='js-content'>

                {% if record.image %}
                    <img src="{{ record.image.url }}" class="img-responsive own-image" alt="Post Imagen">
                {% endif %}

                <div class="well text-justify own-content">
                    {% autoescape off %}
                        {{ record.content|linebreaks }}
                    {% endautoescape %}

                    <div class="own-little-info pull-right">
                        Creado <strong>{{ record.created_date|naturaltime }}</strong>.
                    </div>
                    <br>
                    <br>
                    <div class="text-center">
                        <a href="{% url 'home:landing' %}" class="btn btn-primary">
                            <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
                            Ir a Inicio
                        </a>
                    </div>

                </div>
            </div>

            {% if user.is_superuser or user|check_has_group:"NOTICIAS_ADM" %}
            <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                <div class="panel panel-default affix-top">
                    <div class="panel-heading">
                        <h5 class="panel-title own-panel-title">Otras Acciones:</h5>
                    </div>
                    <ul class="list-group text-center">
                        <a class="list-group-item own-link-item" href="{% url 'editorial:post_edit' record.pk %}">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                            Ir a Edicion
                        </a>
                    </ul>
                </div>
            </div>
            {% endif %}

            <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                <div class="panel panel-default affix-top">
                    <div class="panel-heading">
                        <h5 class="panel-title own-panel-title">Otras Noticias:</h5>
                    </div>
                    {% if other_records %}
                        <ul class="list-group">
                        {% for record in other_records %}
                            <a class="list-group-item own-link-item" href="{% url 'editorial:post_view' record.pk %}">
                                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                {{ record.title }}
                            </a>
                        {% endfor %}
                        </ul>
                    {% else %}
                        <div class="panel-body">
                          <h5 class="text-center">Sin noticias que mostrar</h5>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

{% block scripts %}

    <!-- Own's Scripts -->
    <script type="text/javascript" src="{% static 'post/view.min.js' %}"></script>

{% endblock scripts %}