Prometeus/urls.py
# -*- coding: utf-8 -*-

# Django's Libraries
from django.conf import settings
from django.conf.urls import url
from django.conf.urls import include
from django.conf.urls.static import static

from django.contrib import admin


urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^admin/', admin.site.urls),

    url(r'', include('editorial.urls', namespace="editorial")),
    url(r'', include('home.urls', namespace="home")),
    url(r'', include('labor.urls', namespace="labor")),
    url(r'', include('management.urls', namespace="management")),
    url(r'', include('payroll.urls', namespace="payroll")),
    url(r'', include('security.urls', namespace="security")),

    url(r'api/', include('payroll.urls_rest', namespace="api-payroll")),
    url(r'api/', include('social.urls_rest', namespace="api-social")),
    url(r'api/', include('labor.urls_rest', namespace="api-labor")),
]


if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
# -*- coding: utf-8 -*-

# Django's Libraries
from django.conf.urls import url

# Own's Libraries
from .views import LandingView


urlpatterns = [
    url(r'^$', LandingView.as_view(), name="landing"),
]

payroll/urls.py
# -*- coding: utf-8 -*-

# Django's Libraries
from django.conf.urls import url

# Own's Libraries
from .views import VoucherListView
from .views import VoucherListEdit
from .views import VoucherAdd
from .views import VoucherAddSuccess
from .views import VoucherView
from .views import VoucherEdit
from .views import VoucherCancel

from .views import BenefitListView
from .views import BenefitListEdit
from .views import BenefitCancel
from .views import BenefitAdd
from .views import BenefitAddSuccess
from .views import BenefitEdit


urlpatterns = [

    # Vouchers
    url(
        r'^vouchers/pending/$',
        VoucherListView.as_view(), {'_status': 'pending'},
        name="voucher_list_pending"
    ),
    url(
        r'^vouchers/all/$',
        VoucherListView.as_view(), {'_status': 'all'},
        name="voucher_list_all"
    ),
    url(
        r'^vouchers/admin/pending/$',
        VoucherListEdit.as_view(), {'_status': 'pending'},
        name="voucher_list_admin_pending"
    ),
    url(
        r'^vouchers/admin/all/$',
        VoucherListEdit.as_view(), {'_status': 'all'},
        name="voucher_list_admin_all"
    ),
    url(
        r'^vouchers/add/$',
        VoucherAdd.as_view(),
        name="voucher_add"
    ),
    url(
        r'^vouchers/add/success/$',
        VoucherAddSuccess.as_view(),
        name="voucher_add_success"
    ),
    url(
        r'^vouchers/(?P<pk>\d+)/view/$',
        VoucherView.as_view(),
        name="voucher_view"
    ),
    url(
        r'^vouchers/(?P<pk>\d+)/edit/$',
        VoucherEdit.as_view(),
        name="voucher_edit"
    ),
    url(
        r'^vouchers/(?P<_pk>\d+)/cancel/$',
        VoucherCancel.as_view(),
        name="voucher_cancel"
    ),

    # Benefits
    url(
        r'^benefits/pending/$',
        BenefitListView.as_view(), {'_status': 'pending'},
        name="benefit_list_pending"
    ),
    url(
        r'^benefits/all/$',
        BenefitListView.as_view(), {'_status': 'all'},
        name="benefit_list_all"
    ),
    url(
        r'^benefits/admin/pending/$',
        BenefitListEdit.as_view(), {'_status': 'pending'},
        name="benefit_list_admin_pending"
    ),
    url(
        r'^benefits/admin/all/$',
        BenefitListEdit.as_view(), {'_status': 'all'},
        name="benefit_list_admin_all"
    ),
    url(
        r'^benefits/add/$',
        BenefitAdd.as_view(),
        name="benefit_add"
    ),
    url(
        r'^benefits/add/success/$',
        BenefitAddSuccess.as_view(),
        name="benefit_add_success"
    ),
    url(
        r'^benefits/(?P<pk>\d+)/edit/$',
        BenefitEdit.as_view(),
        name="benefit_edit"
    ),
    url(
        r'^benefits/(?P<pk>\d+)/cancel/$',
        BenefitCancel.as_view(),
        name="benefit_cancel"
    ),
]

payroll/models.py
# -*- coding: utf-8 -*-

# Python's Libraries
from __future__ import unicode_literals

# Django's Libraries
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

# Own's Libraries
from .utilities import Helper
from security.models import Profile
from social.business import CommentBusiness


class VoucherType(models.Model):
    name = models.CharField(
        "Nombre",
        max_length=50,
        blank=False,
        unique=True
    )
    description = models.TextField("Descripción", blank=True, null=True)
    valid_range = models.BooleanField(
        "Validar rangos de fechas",
        default=True
    )

    created_date = models.DateTimeField(
        auto_now=False,
        auto_now_add=True,
    )
    updated_date = models.DateTimeField(
        auto_now=True,
        auto_now_add=False,
    )

    class Meta:
        verbose_name = 'Tipo de Comprobante'
        verbose_name_plural = 'Tipos de Comprobantes'

    def __unicode__(self):
        return self.name


class VoucherRequisition(models.Model):
    STATUS_OPTIONS = (
        ('pen', 'PENDIENTE'),
        ('can', 'CANCELADO'),
        ('com', 'COMPLETADO'),
    )

    employee = models.ForeignKey(
        Profile,
        verbose_name="Empleado",
        blank=False,
        on_delete=models.PROTECT
    )
    type = models.ForeignKey(
        VoucherType,
        verbose_name="Tipo",
        blank=False,
        on_delete=models.PROTECT
    )
    date_start = models.DateField("Fecha Inicio", blank=True, null=True)
    date_end = models.DateField("Fecha Fin", blank=True, null=True)
    reason = models.TextField("Motivo de la Solicitud", blank=True, null=True)
    response = models.TextField(
        "Respuesta de Administracion", blank=True, null=True)
    file = models.FileField(
        "Archivo",
        upload_to=Helper.get_FilePath_Voucher,
        validators=[
            Helper.validate_Size
        ],
        blank=True,
        null=True,
    )
    status = models.CharField(
        "Estado",
        max_length=3,
        choices=STATUS_OPTIONS,
        default="pen"
    )
    created_by = models.ForeignKey(
        Profile,
        verbose_name="Creado por",
        related_name='sc_created_by',
        blank=True,
        null=True
    )
    created_date = models.DateTimeField(
        auto_now=False,
        auto_now_add=True,
    )
    updated_by = models.ForeignKey(
        Profile,
        verbose_name="Actualizado por",
        related_name='sc_updated_by',
        blank=True,
        null=True
    )
    updated_date = models.DateTimeField(
        auto_now=True,
        auto_now_add=False,
    )

    def clean(self):
        fecha_inicio = self.date_start
        fecha_fin = self.date_end
        tipo = self.type

        if tipo.valid_range:
            if fecha_inicio is None:
                raise ValidationError({
                    'date_start': _(
                        'Fecha Inicial no proporcionada.'
                    )
                })

            if fecha_fin is None:
                raise ValidationError({
                    'date_end': _(
                        'Fecha Fin no proporcionada.'
                    )
                })

            if fecha_fin < fecha_inicio:
                raise ValidationError({
                    'date_end': _(
                        'Fecha final no puede ser menor que fecha inicial.'
                    )
                })

    class Meta:
        verbose_name = 'Solicitud de Comprobante'
        verbose_name_plural = 'Solicitudes de Comprobantes'

    def __unicode__(self):
        desc = "%s : %s - %s" % (self.pk, self.employee, self.type)
        return desc

    @property
    def is_Complete(self):
        if self.status == "com":
            return True
        else:
            return False

    @property
    def is_Cancel(self):
        if self.status == "can":
            return True
        else:
            return False

    @property
    def is_Editable(self):
        if self.status == "can" or self.status == "com":
            return False
        else:
            return True

    @property
    def comments(self):
        records = CommentBusiness.get(self.__class__, self.id)
        return records


class BenefitType(models.Model):
    name = models.CharField(
        "Nombre",
        max_length=50,
        blank=False,
        unique=True
    )
    description = models.TextField("Descripción", blank=True, null=True)

    created_date = models.DateTimeField(
        auto_now=False,
        auto_now_add=True,
    )
    updated_date = models.DateTimeField(
        auto_now=True,
        auto_now_add=False,
    )

    class Meta:
        verbose_name = 'Tipo de Prestacion'
        verbose_name_plural = 'Tipos de Prestaciones'

    def __unicode__(self):
        return self.name


class BenefitRequisition(models.Model):
    STATUS = (
        ('pen', 'Pendiente'),
        ('ppe', 'Pago Pendiente'),
        ('ppc', 'Pago Por Comprobar'),
        ('com', 'Completado'),
        ('can', 'Cancelado')
    )

    employee = models.ForeignKey(
        Profile,
        verbose_name="Empleado",
        blank=False,
        on_delete=models.PROTECT
    )
    type = models.ForeignKey(
        BenefitType,
        verbose_name="Tipo",
        blank=False,
        on_delete=models.PROTECT
    )
    date = models.DateField("Fecha")
    reason = models.TextField("Motivo de la Solicitud", blank=True)
    payment_evidence = models.TextField("Evidencia del Pago", blank=True)
    admin_response = models.TextField(
        "Respuesta de Administración",
        blank=True
    )
    payment_info = models.TextField("Informacion del Pago", blank=True)
    status = models.CharField(
        "Estado", max_length=3, choices=STATUS, default="pen")
    created_by = models.ForeignKey(
        Profile,
        verbose_name="Creado por",
        related_name='sp_created_by',
        blank=True,
        null=True
    )
    created_date = models.DateTimeField(
        auto_now=False,
        auto_now_add=True,
    )
    updated_by = models.ForeignKey(
        Profile,
        verbose_name="Actualizado por",
        related_name='sp_updated_by',
        blank=True,
        null=True
    )
    updated_date = models.DateTimeField(
        auto_now=True,
        auto_now_add=False,
    )

    class Meta:
        verbose_name = 'Solicitud de Prestacion'
        verbose_name_plural = 'Solicitudes de Prestaciones'

    def __unicode__(self):
        desc = "%s : %s - %s" % (self.pk, self.employee, self.type)
        return desc

    @property
    def is_Complete(self):
        if self.status == "com":
            return True
        else:
            return False

    @property
    def is_Cancel(self):
        if self.status == "can":
            return True
        else:
            return False

    @property
    def is_Editable(self):
        if self.status == "can" or self.status == "com":
            return False
        else:
            return True

    @property
    def comments(self):
        records = CommentBusiness.get(self.__class__, self.id)
        return records

payroll/forms.py
# -*- coding: utf-8 -*-

# Django's Libraries
from django.forms import ModelForm
from django.forms import Select
# from django.forms import TextInput
from django.forms import FileInput
from django.forms import DateInput
from django.forms import Textarea
from django.forms import ValidationError

# Own's Libraries
from .models import VoucherRequisition, BenefitRequisition


class VoucherRequisitionAddForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(VoucherRequisitionAddForm, self).__init__(*args, **kwargs)
        self.fields['reason'].required = True

    class Meta:
        model = VoucherRequisition
        fields = (
            'type',
            'date_start',
            'date_end',
            'reason',
        )
        exclude = [
            'employee',
            'response',
            'is_complete',
        ]

        widgets = {
            'date_start': DateInput(
                attrs={'class': 'form-control'},
                format='%d/%m/%Y'
            ),
            'date_end': DateInput(
                attrs={'class': 'form-control'},
                format='%d/%m/%Y'
            ),
            'type': Select(attrs={'class': 'form-control'}),
            'reason': Textarea(attrs={'class': 'form-control', 'rows': '8'}),
        }

        labels = {
            'type': 'Tipo de comprobante:',
            'reason': 'Motivo:'
        }


class VoucherRequisitionEditForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(VoucherRequisitionEditForm, self).__init__(*args, **kwargs)
        instance = kwargs['instance']        
        self.fields['response'].required = True
        if instance.status == 'can' or instance.status == 'com':
            self.fields['status'].widget.attrs['readonly'] = True
            self.fields['file'].widget.attrs['readonly'] = True
            self.fields['response'].widget.attrs['readonly'] = True

    class Meta:
        model = VoucherRequisition
        fields = (
            'file',
            'status',
            'response',
        )
        exclude = [
            'employee',
            'type',
            'date_start',
            'date_end',
            'reason',
            'created_by',
            'created_date',
            'updated_by',
            'updated_date',
        ]
        widgets = {
            'file': FileInput(attrs={
                'class': 'filestyle',
                'data-iconName': 'glyphicon glyphicon-file',
                'data-buttonText': 'Seleccionar Archivo'
            }),
            'status': Select(attrs={'class': 'form-control'}),
            'response': Textarea(attrs={'class': 'form-control', 'rows': '8'}),
        }
        labels = {
            'file': 'Archivo',
            'status': 'Estado',
            'response': 'Respuesta',
        }

    def clean(self):
        status = self.cleaned_data['status']
        file = self.cleaned_data['file']
        response = self.cleaned_data['response']

        if status == "com":
            if file is None:
                raise ValidationError(
                    "No se puede marcar como Completado "
                    "sin adjuntar un archivo"
                )

            if response == "":
                raise ValidationError(
                    "Favor de dar una respuesta al Empleado"
                )

        if status == "can" and response == "":
            raise ValidationError(
                "Favor de dar explicar porque estas cancelando la solicitud"
            )


class BenefitRequisitionAddForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(BenefitRequisitionAddForm, self).__init__(*args, **kwargs)
        self.fields['reason'].required = True

    class Meta:
        model = BenefitRequisition
        fields = (
            'type',
            'date',
            'reason',
        )
        widgets = {
            'date': DateInput(
                attrs={'class': 'form-control'},
                format='%d/%m/%Y'
            ),
            'type': Select(attrs={'class': 'form-control'}),
            'reason': Textarea(attrs={'class': 'form-control', 'rows': '8'}),
        }

        labels = {
            'type': 'Tipo de Prestacion:',
            'reason': 'Motivo:'
        }


class BenefitRequisitionEditForm(ModelForm):
    user_fields = ['payment_evidence', ]  # Fill with user fillable fields.

    def __init__(self, is_admin_form=False, is_cancelled=False, *args, **kwargs):
        super(BenefitRequisitionEditForm, self).__init__(*args, **kwargs)
        self.fields['status'].required = False
        if not is_cancelled:
            if is_admin_form:
                for field in [x for x in self.fields if x in self.user_fields]:
                    self.fields[field].widget.attrs['readonly'] = True
            else:
                for field in [x for x in self.fields if not x in self.user_fields]:
                    self.fields[field].widget.attrs['readonly'] = True
        else:
            for field in self.fields:
                self.fields[field].widget.attrs['readonly'] = True

    class Meta:
        model = BenefitRequisition
        fields = [
            "payment_info",
            'status',
            'payment_evidence',
            'admin_response',
        ]
        widgets = {
            "payment_info": Textarea(attrs={'class': 'form-control', 'rows': '8'}),
            "admin_response": Textarea(attrs={'class': 'form-control', 'rows': '8'}),
            "payment_evidence": Textarea(attrs={'class': 'form-control', 'rows': '8'}),
            'status': Select(attrs={'class': 'form-control'}),
        }
        labels = {
            "payment_info": 'Información del pago',
            "payment_evidence": 'Evidencia del pago',
            "admin_response": 'Respuesta del administrador',
            'status': 'Estado de la operación',
        }

payroll/templates/benefit_add.html
{% extends 'master.html' %}
{% load static from staticfiles %}
{% load custom_tags %}
{% block title %} GCM - Nuevo Solicitud de Prestacion {% endblock title %}

{% block css %}

    <!-- Bootstrap Select -->
    <link rel="stylesheet" type="text/css" href="{% static 'libs/select2/4.0.3/dist/css/select2.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'libs/select2-bootstrap-theme-master/0.1.0-beta.10/dist/select2-bootstrap.min.css' %}"/>

    <!-- Bootrstrap DatePicker -->
    <link rel="stylesheet" type="text/css" href="{% static 'libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker3.min.css' %}"/>

    <!-- Own's Styles -->
    <link rel="stylesheet" type="text/css" href="{% static 'tags/forms.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'tags/components.min.css' %}"/>

{% endblock css %}

{% block content %}

    <div class="container own-components-area">
    	<div class="row">

            <div class="col-xs-12">
                <header>
                    <h3>
                        <ol class="breadcrumb own-breadcrumb">
                          <li class="own-breadcrumb-init"><a href="{% url 'payroll:benefit_list_all' %}">Solicitudes</a></li>
                          <li>Solicitud de Prestacion</li>
                        </ol>
                    </h3>
                </header>
                <hr>
    		</div>

            <div class="col-xs-12">
                <div class="own-form-title">
                    Proporciona la siguiente información:
                </div>

                <form action=""
                method="post"
                class="well"
                enctype="multipart/form-data"> {% csrf_token %}

                    {% include 'messages.html' %}

                    {% tag_form_errors form %}

                    {% tag_field form.type %}

                    {% tag_date 'Fecha' False form.date %}

                    {% tag_field form.reason %}

                    <div class="text-center">
                        <a href="{% url 'payroll:benefit_list_all' %}" class="btn btn-default">Cancelar</a>
                        <button type="submit" class="btn btn-success">
                            <span class="glyphicon glyphicon-ok"></span>
                            Solicitar
                        </button>
                    </div>

                </form>
            </div>
    	</div>
    </div>

{% endblock content %}

{% block scripts %}

	<!-- Bootstrap Select -->
	<script type="text/javascript" src="{% static 'libs/select2/4.0.3/dist/js/select2.min.js' %}"></script>

	<!-- Bootrstrap DatePicker -->
	<script type="text/javascript" src="{% static 'libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.min.js' %}"></script>

	<!-- Own's Scripts -->
	<script type="text/javascript" src="{% static 'benefit_add.js' %}"></script>

{% endblock scripts %}

payroll/templates/benefit_add_success.html
{% extends 'master.html' %}

{% load static from staticfiles %}

{% block css %}

{% endblock css %}

{% block content %}

    <div class="container">
        <div class="row">

            <div class="col-xs-12">
                <div class="jumbotron text-center">
                    <h1>Solicitud de prestación enviada</h1>

                    <p>
                    	El equipo del departamento de nómina procesará tu solicitud.
                    </p>

                    <a href="{% url 'payroll:benefit_list_all' %}" class="btn btn-default">
                        Ver lista de solicitudes de prestaciones
                    </a>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

{% block scripts %}

{% endblock scripts %}

payroll/templates/benefit_cancel.html
{% extends 'master.html' %}

{% load static from staticfiles %}

{% block css %}

{% endblock css %}

{% block content %}

    <div class="container">
        <div class="row">
            <form action=""
            method="post"
            enctype="multipart/form-data"> {% csrf_token %}
                <div class="col-xs-12">
                    <div class="jumbotron text-center">
                        <h1>¿Esta seguro de cancelar esta solicitud?</h1>

                        <p>
                        	Si cancela esta solicitud, se enviara correo a personal de nomina para detener el proceso de la solicitud
                        </p>

                        <a href="{% url 'payroll:benefit_list_all' %}" class="btn btn-default">
                            No, Regresar a listado
                        </a>

                        <button type="submit" class="btn btn-danger">
                            <span class="glyphicon glyphicon-ok"></span>
                            Si, Cancelar
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock content %}

{% block scripts %}

{% endblock scripts %}

payroll/templates/benefit_list_admin.html
{% extends 'master.html' %}

{% load static from staticfiles %}

{% load humanize %}
{% load filter_has_group from custom_tags %}
{% block title %} GCM - Prestaciones{% endblock %}
{% block css %}

    <!-- Own's Styles -->
    <link rel="stylesheet" href="{% static 'voucher/list.min.css' %}" />
    <link rel="stylesheet" href="{% static 'custom.css' %}">

{% endblock css %}

{% block content %}

    <div class="container-fluid">

           <header>
                <h3 class="own-titulo">Prestaciones</h3>
            </header>

            <hr class="own-article-line">

            <nav class="own-article-toolbar">

                <div class="row">

                    <div class="col-xs-12 col-sm-6">
                        <a href="{% url 'payroll:benefit_add' %}" class="btn btn-primary ">
                            <i class="fa fa-plus-circle" aria-hidden="true"></i>
                            Solicitar
                        </a>
                        {% if status == 'all' %}
                            <a href="{% url 'payroll:benefit_list_admin_pending' %}" class="btn btn-info ">
                                <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
                                Ver solo pendientes
                            </a>
                        {% else %}
                            <a href="{% url 'payroll:benefit_list_admin_all' %}" class="btn btn-info ">
                                <span class="glyphicon glyphicon-th" aria-hidden="true"></span>
                                Ver todos
                            </a>
                        {% endif %}
                    </div>

                    <br class="visible-xs">
                    <br class="visible-xs">

                    <form class="col-xs-12 col-sm-6" action="" method="GET">

                        <div class="input-group">
                            <input type="text" class="form-control" name="q" placeholder="escribe texto a buscar" value="{{ request.GET.q }}">

                            <span class="input-group-btn">
                              <button type="submit" id="boton_buscar" class="btn btn-info btn-flat">
                                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                                <span class="hidden-xs">Buscar</span>
                              </button>
                            </span>
                        </div>

                    </form>
                </div>
            </nav>

            <br>

            <div class="container-fluid">
            {% if requisitions %}

                <div class="row own-record-titles">

                    <div class="col-sm-4 col-md-6">TIPO</div>

                    <div class="col-sm-1 col-md-1">ESTADO</div>

                    <div class="col-sm-3 col-md-2">FECHA</div>

                    <div class="col-sm-3 col-md-2">FECHA SOLICITUD</div>

                    <div class="col-sm-1 col-md-1"></div>
                </div>

                {% for requisition in requisitions %}
                    <div class="row own-record">

                        <!-- Tipo y Estado -->
                        <div class="visible-xs col-sm-5 own-column-pk
                            {% if requisition.status == 'com' %}
                                own-column-pk-success
                            {% elif requisition.status == 'can' %}
                                own-column-pk-cancel
                            {% else %}
                                own-column-pk-warning
                            {% endif %}">
                            {{requisition.type}} - {{requisition.pk}}

                            <span class="own-column-conten pull-right">
                                {% if requisition.status == 'com' %}
                                    <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                                {% elif requisition.status == 'can' %}
                                    <span class="glyphicon glyphicon-minus-sign" aria-hidden="true"></span>
                                {% else %}
                                    <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
                                {% endif %}
                            </span>
                        </div>

                        <!-- Tipo y Nombre -->
                        <div class="col-sx-12 col-sm-4 col-md-6 own-column-main own-column--border">

                            <div class="row">
                                <div class="hidden-xs col-sm-12 col-md-5 own-data-second">
                                    {{requisition.pk}} - {{requisition.type}}
                                </div>
                                <div class="col-sx-12 col-sm-12 col-md-7 own-data-second">
                                    <a href="{% url 'security:profile' requisition.employee.pk %}">
                                        {{ requisition.employee }}
                                    </a>
                                </div>
                            </div>
                        </div>

                        <!-- Estado -->
                        <div class="hidden-xs col-sm-1 own-column text-center own-column--border own-column-estado">
                            <span class="own-column-conten" title="{{ requisition.get_status_display }}">

                                {% if requisition.status == 'com' %}
                                    <span class="glyphicon glyphicon-ok-sign own-data-icon-success" aria-hidden="true"></span>
                                {% elif requisition.status == 'can' %}
                                    <span class="glyphicon glyphicon-minus-sign own-data-icon-cancel" aria-hidden="true"></span>
                                {% else %}
                                    <span class="glyphicon glyphicon-time own-data-icon-warning" aria-hidden="true"></span>
                                {% endif %}
                            </span>
                        </div>

                        <!-- Fecha Informacion -->
                        <div class="col-sx-12 col-sm-3 col-md-2 own-column own-column-range own-column--border">
                            <span class="own-data-label" >
                                Fecha:
                            </span>
                            <span class="glyphicon glyphicon-calendar own-data-icon" aria-hidden="true"></span>
                            <span class="own-data-normalvalue">
                                {{requisition.date|date:"d M Y"}}
                            </span>
                        </div>

                        <!-- Fecha Solicitud -->
                        <div class="col-sx-12 col-sm-3 col-md-2 own-column own-column--border">
                            <span class="own-data-label" >
                                Fecha Solicitud:
                            </span>
                            <span class="glyphicon glyphicon-calendar own-data-icon" aria-hidden="true"></span>
                            <span class="own-data-normalvalue">
                                {{requisition.created_date|naturaltime|default:"" }}
                            </span>
                        </div>

                        <!-- Comand -->
                        <a href="{% url 'payroll:benefit_edit' requisition.pk %}" class="col-sx-12 col-sm-1 col-md-1 own-column own-comando">

                            <span class="glyphicon glyphicon-edit own-link-icon" aria-hidden="true"></span>
                            <span class="own-data-normalvalue own-data-comandvalue">
                                Editar
                            </span>
                        </a>

                    </div>
                {% endfor %}

                <div class="text-center">
                    <ul class="pagination pagination-sm no-margin">
                        {% if requisitions.has_previous %}
                            <li><a href="?{{ page_request_var }}={{ requisitions.previous_page_number }}&q={{ request.GET.q }}">&laquo;</a></li>
                        {% endif %}

                        {% for i in requisitions.paginator.page_range %}
                            <li {% if requisitions.number == i %} class="active own-active" {% endif %}>
                                <a href="?page={{i}}&q={{ request.GET.q }}">{{ i }}</a>
                            </li>
                        {% endfor %}

                        {% if requisitions.has_next %}
                            <li><a href="?page={{ requisitions.next_page_number }}&q={{ request.GET.q }}">&raquo;</a></li>
                        {% endif %}
                    </ul>
                </div>

            {% else %}
                <h1 class="text-center">Sin solicitudes</h1>
            {% endif %}
        </div>

    </div>

{% endblock content %}

{% block scripts %}
{% endblock scripts %}