Prometeus/urls.py
# -*- coding: utf-8 -*-

# Django's Libraries
from django.conf import settings
from django.conf.urls import url
from django.conf.urls import include
from django.conf.urls.static import static

from django.contrib import admin


urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^admin/', admin.site.urls),

    url(r'', include('editorial.urls', namespace="editorial")),
    url(r'', include('home.urls', namespace="home")),
    url(r'', include('labor.urls', namespace="labor")),
    url(r'', include('management.urls', namespace="management")),
    url(r'', include('payroll.urls', namespace="payroll")),
    url(r'', include('security.urls', namespace="security")),

    url(r'api/', include('payroll.urls_rest', namespace="api-payroll")),
    url(r'api/', include('social.urls_rest', namespace="api-social")),
    url(r'api/', include('labor.urls_rest', namespace="api-labor")),
]


if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
# -*- coding: utf-8 -*-

# Django's Libraries
from django.conf.urls import url

# Own's Libraries
from .views import LandingView


urlpatterns = [
    url(r'^$', LandingView.as_view(), name="landing"),
]

labor/urls.py
# -*- coding: utf-8 -*-

# Django's Libraries
from django.conf.urls import url

# Own's Libraries
from .views import IncidentListView
from .views import IncidentListEdit
from .views import IncidentAdd
from .views import IncidentAddSuccess
from .views import IncidentAddEvidence
from .views import IncidentView
from .views import IncidentEdit
from .views import IncidentCancel


urlpatterns = [
    url(
        r'^incidents/pending/$',
        IncidentListView.as_view(), {'_status': 'pending'},
        name="incident_list_pending"
    ),
    url(
        r'^incidents/all/$',
        IncidentListView.as_view(), {'_status': 'all'},
        name="incident_list_all"
    ),
    url(
        r'^incidents/admin/pending/$',
        IncidentListEdit.as_view(), {'_status': 'pending'},
        name="incident_list_admin_pending"
    ),
    url(
        r'^incidents/admin/all/$',
        IncidentListEdit.as_view(), {'_status': 'all'},
        name="incident_list_admin_all"
    ),
    url(
        r'^incidents/add/$',
        IncidentAdd.as_view(),
        name="incident_add"
    ),
    url(
        r'^incidents/(?P<pk>\d+)/evidence/add/$',
        IncidentAddEvidence.as_view(),
        name="incident_add_evidence"
    ),
    url(
        r'^incidents/add/success/$',
        IncidentAddSuccess.as_view(),
        name="incident_add_success"
    ),
    url(
        r'^incidents/(?P<pk>\d+)/view/$',
        IncidentView.as_view(),
        name="incident_view"
    ),
    url(
        r'^incidents/(?P<pk>\d+)/edit/$',
        IncidentEdit.as_view(),
        name="incident_edit"
    ),
    url(
        r'^incidents/(?P<pk>\d+)/cancel/$',
        IncidentCancel.as_view(),
        name="incident_cancel"
    ),
]

labor/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

# Python's Libraries
from __future__ import unicode_literals

# Django's Libraries
from django.db import models

# Third-party Libraries
from django_resized import ResizedImageField

# Own's Libraries
from security.models import Profile
from social.business import CommentBusiness
from .utilities import Helper


class IncidentType(models.Model):
    name = models.CharField(
        "Nombre",
        max_length=50,
        blank=False,
        unique=True
    )
    description = models.TextField("Descripción", blank=True, null=True)
    evidence_required = models.BooleanField("Requerir evidencia", default=True)

    created_date = models.DateTimeField(
        auto_now=False,
        auto_now_add=True,
    )
    updated_date = models.DateTimeField(
        auto_now=True,
        auto_now_add=False,
    )

    class Meta:
        verbose_name = 'Tipo de Incidencia'
        verbose_name_plural = 'Tipos de Incidencia'

    def __unicode__(self):
        return self.name


class IncidentReport(models.Model):
    STATUS_OPTIONS = (
        ('inc', 'INCOMPLETO'),
        ('pen', 'PENDIENTE'),
        ('can', 'CANCELADO'),
        ('com', 'PROCESADO'),
    )

    employee = models.ForeignKey(
        Profile,
        verbose_name="Empleado",
        blank=False,
        on_delete=models.PROTECT
    )
    type = models.ForeignKey(
        IncidentType,
        verbose_name="Tipo",
        blank=False,
        on_delete=models.PROTECT
    )
    date = models.DateField("Fecha", blank=True, null=True)
    reason = models.TextField("Motivo de la Solicitud", blank=True)
    response = models.TextField("Respuesta de Administracion", blank=True)
    file = models.FileField(
        "Archivo",
        upload_to=Helper.get_FilePath_Incident,
        validators=[
            Helper.validate_Size
        ],
        blank=True,
        null=True,
    )
    status = models.CharField(
        "Estado",
        max_length=3,
        choices=STATUS_OPTIONS,
        default="pen"
    )
    created_by = models.ForeignKey(
        Profile,
        verbose_name="Creado por",
        related_name='si_created_by',
        blank=True,
        null=True
    )
    created_date = models.DateTimeField(
        auto_now=False,
        auto_now_add=True,
    )
    updated_by = models.ForeignKey(
        Profile,
        verbose_name="Actualizado por",
        related_name='si_updated_by',
        blank=True,
        null=True
    )
    updated_date = models.DateTimeField(
        auto_now=True,
        auto_now_add=False,
    )

    class Meta:
        verbose_name = 'Reporte de Incidencia'
        verbose_name_plural = 'Reportes de Incidencias'

    def __unicode__(self):
        desc = "%s : %s - %s" % (self.pk, self.employee, self.type)
        return desc

    @property
    def is_Complete(self):
        if self.status == "com":
            return True
        else:
            return False

    @property
    def is_Cancel(self):
        if self.status == "can":
            return True
        else:
            return False

    @property
    def is_Editable(self):
        if self.status == "can" or self.status == "com":
            return False
        else:
            return True

    @property
    def comments(self):
        records = CommentBusiness.get(self.__class__, self.id)
        return records


class IncidentEvidence(models.Model):
    incident = models.ForeignKey(
        IncidentReport,
        verbose_name="Reporte de Incidencia",
        blank=True,
        null=True
    )
    image = ResizedImageField(
        "Foto",
        upload_to=Helper.get_ImagePath_Evidence,
        quality=75,
        blank=True,
        keep_meta=False,
        validators=[
            Helper.validate_Img_Extension,
            Helper.validate_Size
        ]
    )
    uploaded_at = models.DateTimeField(auto_now_add=True)

labor/views.py
# -*- coding: utf-8 -*-

# Python's Libraries
from __future__ import unicode_literals

# Django's Libraries
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.views.generic.base import View
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.contrib import messages


# Own's Libraries
from security.mixins import GroupLoginRequiredMixin
from management.postman import IncidentMail

from .business import IncidentReportBusiness as IncidentBusiness
from .models import IncidentReport
from .forms import IncidentReportAddForm
from .forms import IncidentReportEditForm


class IncidentListView(GroupLoginRequiredMixin, View):
    template_name = "incident/list_for_review.html"
    group = ['INCIDENCIAS_ADM', 'INCIDENCIAS_USR', ]

    def get(self, _request, _status):
        query = _request.GET.get('q')

        if _status == 'pending':
            records = IncidentBusiness.get_Pending(
                query,
                _request.user.profile
            )
        else:
            records = IncidentBusiness.get_All(
                query,
                _request.user.profile
            )

        records_paginated = IncidentBusiness.get_Paginated(
            records,
            _request.GET.get('page')
        )
        context = {
            'records': records_paginated
        }
        return render(_request, self.template_name, context)


class IncidentListEdit(GroupLoginRequiredMixin, View):
    template_name = "incident/list_for_edit.html"
    group = ['INCIDENCIAS_ADM', ]

    def get(self, _request, _status):
        query = _request.GET.get('q')

        if _status == 'pending':
            records = IncidentBusiness.get_Pending(query)
        else:
            records = IncidentBusiness.get_All(query)

        records_paginated = IncidentBusiness.get_Paginated(
            records,
            _request.GET.get('page')
        )
        context = {
            'records': records_paginated
        }
        return render(_request, self.template_name, context)


class IncidentAdd(GroupLoginRequiredMixin, CreateView):
    template_name = "incident/add.html"
    model = IncidentReport
    form_class = IncidentReportAddForm
    group = ['INCIDENCIAS_ADM', 'INCIDENCIAS_USR', ]

    def form_valid(self, form):
        form.instance.employee = self.request.user.profile
        form.instance.created_by = self.request.user.profile
        form.instance.updated_by = self.request.user.profile

        if form.instance.type.evidence_required:
            form.instance.status = 'inc'
        else:
            form.instance.status = 'pen'

        response = super(IncidentAdd, self).form_valid(form)
        return response

    def get_success_url(self, **kwargs):
        return reverse_lazy(
            'labor:incident_add_evidence',
            args=(self.object.pk,)
        )


class IncidentAddEvidence(GroupLoginRequiredMixin, View):
    template_name = "incident/add_evidence.html"
    group = ['INCIDENCIAS_ADM', 'INCIDENCIAS_USR', ]

    def get(self, _request, pk):
        record = get_object_or_404(IncidentReport, pk=pk)
        evidences = record.incidentevidence_set.all()
        context = {
            'record': record,
            'evidences': evidences
        }
        return render(_request, self.template_name, context)

    def post(self, _request, pk):
        record = get_object_or_404(IncidentReport, pk=pk)
        evidences = record.incidentevidence_set.all()

        if record.type.evidence_required:
            if len(evidences) > 0:
                record.status = "pen"
                record.save()

                self.request.user.email_user(
                    "Tu Reporte con el no. %s fue CREADO correctamente" %
                    (record.pk),
                    "La Administracion revisara tu reporte "
                    "y se te avisara por este medio la revion del mismo."
                )

                IncidentMail.send(
                    _type=record.type,
                    _subject="%s genero un nuevo reporte con el no. %s" % (
                        record.employee.user.get_full_name(),
                        record.pk
                    ),
                    _content="Estimado Administrador,\nEl empleado %s registro"
                    " la solicitud #%s, informando de una incidencia de %s. "
                    "Favor de entrar a plataforma para revisar y procesar" %
                    (
                        record.employee.user.get_full_name(),
                        record.pk,
                        record.type.name
                    )
                )

                return redirect(reverse('labor:incident_add_success'))
            else:
                messages.error(
                    _request,
                    "Se require al menos una imagen de evidencia"
                )
        else:

            return redirect(reverse('labor:incident_add_success'))

        context = {
            'record': record,
            'evidences': evidences
        }

        return render(_request, self.template_name, context)


class IncidentAddSuccess(GroupLoginRequiredMixin, TemplateView):
    template_name = "incident/add_success.html"
    group = ['INCIDENCIAS_ADM', 'INCIDENCIAS_USR', ]


class IncidentCancel(GroupLoginRequiredMixin, View):
    template_name = "incident/cancel.html"
    group = ['INCIDENCIAS_ADM', 'INCIDENCIAS_USR', ]

    def get(self, _request, pk):
        record = get_object_or_404(IncidentReport, pk=pk)
        context = {
            'record': record
        }
        return render(_request, self.template_name, context)

    def post(self, _request, pk):
        record = get_object_or_404(IncidentReport, pk=pk)
        record.updated_by = _request.user.profile
        record.status = "can"
        record.save()

        record.employee.user.email_user(
            "Tu Reporte con el no. %s fue CANCELADO correctamente" %
            (record.pk),
            "Se avisara a la Administracion para que no siga dando "
            "seguimiento a tu reporte"
        )

        IncidentMail.send(
            _type=record.type,
            _subject="%s CANCELO el reporte con el no. %s" % (
                record.employee.user.get_full_name(),
                record.pk
            ),
            _content="Estimado Administrador, \nSe CANCELO el reporte #%s."
            "No es necesario que le siga dando seguimiento." %
            (record.pk),
        )

        return redirect(reverse('labor:incident_list_all'))


class IncidentView(GroupLoginRequiredMixin, DetailView):
    model = IncidentReport
    template_name = "incident/view.html"
    group = ['INCIDENCIAS_ADM', 'INCIDENCIAS_USR', ]
    context_object_name = "record"

    def get_context_data(self, **kwargs):
        context = {}
        if self.object:
            context['object'] = self.object
            context_object_name = self.get_context_object_name(self.object)
            if context_object_name:
                context[context_object_name] = self.object
        context.update(kwargs)
        return super(IncidentView, self).get_context_data(**context)


class IncidentEdit(GroupLoginRequiredMixin, UpdateView):
    model = IncidentReport
    template_name = "incident/edit.html"
    group = ['INCIDENCIAS_ADM', ]
    form_class = IncidentReportEditForm
    success_url = reverse_lazy('labor:incident_list_admin_pending')

    def form_valid(self, form):
        form.instance.updated_by = self.request.user.profile
        response = super(IncidentEdit, self).form_valid(form)

        if response.status_code == 302:
            if form.instance.status == "can":
                form.instance.employee.user.email_user(
                    "La Administracion CANCELO tu reporte con no. %s" %
                    (form.instance.pk),
                    "La Administracion CANCELO tu reporte dejando el "
                    "siguiente motivo: \n - '%s'" % (
                        form.instance.response
                    )
                )

                IncidentMail.send(
                    _type=form.instance.type,
                    _subject="Se CANCELO el reporte con el no. %s" %
                    (form.instance.pk),
                    _content="Estimado Administrador, \n"
                    "se CANCELO el reporte #%s. "
                    "No es necesario que le siga dando seguimiento." %
                    (form.instance.pk)
                )

            elif form.instance.status == "com":
                form.instance.employee.user.email_user(
                    "La Administracion PROCESO tu reporte con no. %s" %
                    (form.instance.pk),
                    "La Administracion PROCESO tu reporte dejando el "
                    "siguiente mensaje: \n - '%s' \n - Archivo: %s" % (
                        form.instance.response,
                        "http://" +
                        self.request.get_host() +
                        form.instance.file.url
                    )
                )

                IncidentMail.send(
                    _type=form.instance.type,
                    _subject="Se PROCESO el reporte con el no. %s" %
                    (form.instance.pk),
                    _content="Estimado Administrador, \n"
                    "se PROCESO el reporte #%s."
                    " No es necesario que le siga dando seguimiento." %
                    (form.instance.pk)
                )

        return response

    def form_invalid(self, form):
        update_obj = IncidentReport.objects.get(id=form.instance.pk)
        form.instance = update_obj
        return self.render_to_response(self.get_context_data(form=form))

labor/templates/incident/add.html
{% extends 'master_in.html' %}
{% load static from staticfiles %}
{% load forms %}
{% load feedback %}
{% block title %} GCM - Nuevo Reporte de Incidencia {% endblock title %}

{% block css %}

    <!-- Alertify -->
    <link rel="stylesheet" type="text/css" href="{% static 'libs/alertifyjs/1.11.0/css/alertify.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'libs/alertifyjs/1.11.0/css/themes/bootstrap.min.css' %}"/>

    <!-- Bootstrap Select -->
    <link rel="stylesheet" type="text/css" href="{% static 'libs/select2/4.0.3/dist/css/select2.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'libs/select2-bootstrap-theme-master/0.1.0-beta.10/dist/select2-bootstrap.min.css' %}"/>

    <!-- Bootrstrap DatePicker -->
    <link rel="stylesheet" type="text/css" href="{% static 'libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker3.min.css' %}"/>

    <!-- Own's Styles -->
    <link rel="stylesheet" type="text/css" href="{% static 'tags/forms.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'tags/components.min.css' %}"/>

{% endblock css %}

{% block content %}

    <div class="container own-components-area">
    	<div class="row">

            <div class="col-xs-12">
                <header>
                    <h3>
                        <ol class="breadcrumb own-breadcrumb">
                          <li class="own-breadcrumb-init"><a href="{% url 'labor:incident_list_all' %}">Reportes</a></li>
                          <li>Reporte de Incidencia</li>
                        </ol>
                    </h3>
                </header>
                <hr>
    		</div>

            <div class="col-xs-12">
                <div class="own-form-title">
                    Proporciona la siguiente información:
                </div>

                <form action=""
                method="post"
                class="well"
                enctype="multipart/form-data"> {% csrf_token %}

                    {% tag_messages messages %}

                    {% tag_form_errors form %}

                    {% tag_field form.type %}

                    {% tag_date 'Fecha' False form.date %}

                    {% tag_field form.reason %}

                    <div class="text-center">
                        <a href="{% url 'labor:incident_list_all' %}" class="btn btn-default">Cancelar</a>
                        <button type="submit" class="btn btn-success" id="btn_submit">
                            <span class="glyphicon glyphicon-ok"></span>
                            Guardar
                        </button>
                    </div>

                </form>
            </div>
    	</div>
    </div>

{% endblock content %}

{% block scripts %}

    <!-- Alertify -->
    <script src="{% static 'libs/alertifyjs/1.11.0/alertify.min.js' %}"></script>
    <script src="{% static 'alerts.min.js' %}"></script>

    <!-- Bootstrap Select -->
    <script type="text/javascript" src="{% static 'libs/select2/4.0.3/dist/js/select2.min.js' %}"></script>

    <!-- Bootrstrap DatePicker -->
    <script type="text/javascript" src="{% static 'libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.min.js' %}"></script>

    <!-- Own's Scripts -->
    <script type="text/javascript" src="{% static 'incident/add.js' %}"></script>

{% endblock scripts %}

labor/templates/incident/add_success.html
{% extends 'master_in.html' %}

{% load static from staticfiles %}

{% block content %}

    <div class="container">
        <div class="row">

            <div class="col-xs-12">
                <div class="jumbotron text-center">
                    <h1>Reporte de Incidencia enviado</h1>
                    <p>
                        El equipo del Calidad revisara el reporte y emitira los comentarios pertinentes.
                    </p>
                    <a href="{% url 'labor:incident_list_all' %}" class="btn btn-default">
                        Ver lista de Reportes de Incidencia
                    </a>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

{% block scripts %}

{% endblock scripts %}

labor/templates/incident/cancel.html
{% extends 'master_in.html' %}

{% load static from staticfiles %}

{% block content %}

    <div class="container">
        <div class="row">
            <form action=""
            method="post"
            enctype="multipart/form-data"> {% csrf_token %}
                <div class="col-xs-12">
                    <div class="jumbotron text-center">
                        <h1>¿Esta seguro de cancelar este Reporte?</h1>

                        <p>
                        	Si cancela esta documento, se enviara correo a personal de Calidad para detener el proceso de seguimiento
                        </p>

                        <a href="{% url 'labor:incident_list_all' %}" class="btn btn-default">
                            No, Regresar a listado
                        </a>

                        <button type="submit" class="btn btn-danger">
                            <span class="glyphicon glyphicon-ok"></span>
                            Si, Cancelar
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock content %}

labor/templates/incident/list_for_review.html
{% extends 'master_in.html' %}

{% load static from staticfiles %}

{% load humanize %}

{% block title %} GCM - Incidencia {% endblock title %}

{% block css %}

    <!-- Own's Styles -->
    <link rel="stylesheet" href="{% static 'incident/list.min.css' %}" />

{% endblock css %}

{% block content %}

    <div class="container-fluid">
        <header>
            <h3 class="own-titulo">Incidencias</h3>
        </header>
        <hr>
        <nav>
            <div class="row">
                <div class="col-xs-12 col-sm-6">
                    <a href="{% url 'labor:incident_add' %}" class="btn btn-primary ">
                        <i class="fa fa-plus-circle" aria-hidden="true"></i>
                        Solicitar
                    </a>

                    {% if request.path == '/incidents/all/' %}
                        <a href="{% url 'labor:incident_list_pending' %}" class="btn btn-info ">
                            <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
                            Ver solo pendientes
                        </a>
                    {% else %}
                        <a href="{% url 'labor:incident_list_all' %}" class="btn btn-info ">
                            <span class="glyphicon glyphicon-th" aria-hidden="true"></span>
                            Ver todos
                        </a>
                    {% endif %}
                </div>
                <br class="hidden-sm hidden-md hidden-lg">
                <br class="hidden-sm hidden-md hidden-lg">
                <form class="col-xs-12 col-sm-6" action="" method="GET">
                    <div class="input-group">
                        <input type="text" class="form-control" name="q" placeholder="escribe texto a buscar" value="{{ request.GET.q }}">

                        <span class="input-group-btn">
                          <button type="submit" id="boton_buscar" class="btn btn-info btn-flat">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                            <span class="hidden-xs">Buscar</span>
                          </button>
                        </span>
                    </div>
                </form>
            </div>
        </nav>
        <br>
        <br class="hidden-xs">

        <div class="container-fluid">
            {% if records %}

                <div class="row own-record-titles">

                    <div class="col-sm-4 col-md-6">TIPO</div>

                    <div class="col-sm-1 col-md-1">ESTADO</div>

                    <div class="col-sm-3 col-md-2">FECHA INFORMACION</div>

                    <div class="col-sm-3 col-md-2">FECHA SOLICITUD</div>

                    <div class="col-sm-1 col-md-1"></div>
                </div>

                {% for record in records %}
                    <div class="row own-record">

                        <!-- Tipo y Estado -->
                        <div class="visible-xs col-sm-5 own-column-pk
                            {% if record.is_Complete %}
                                own-column-pk-success
                            {% elif record.is_Cancel %}
                                own-column-pk-cancel
                            {% elif record.status == 'pen' %}
                                own-column-pk-warning
                            {% else %}
                                own-column-pk-info
                            {% endif %}">
                            {{record.type}} - {{record.pk}}

                            <span class="own-column-conten pull-right">
                                {% if record.is_Complete %}
                                    <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                                {% elif record.is_Cancel %}
                                    <span class="glyphicon glyphicon-minus-sign" aria-hidden="true"></span>
                                {% elif record.status == 'pen' %}
                                    <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
                                {% else %}
                                    <span class="glyphicon glyphicon-adjust" aria-hidden="true"></span>
                                {% endif %}
                            </span>
                        </div>

                        <!-- Tipo y Nombre -->
                        <div class="col-sx-12 col-sm-4 col-md-6 own-column-main own-column--border">

                            <div class="row">
                                <div class="hidden-xs col-sm-12 col-md-5 own-data-second">
                                    {{record.pk}} - {{record.type}}
                                </div>
                                <div class="col-sx-12 col-sm-12 col-md-7 own-data-second">
                                    <strong>{{ record.reason|truncatechars:30 }}</strong>
                                </div>
                            </div>
                        </div>

                        <!-- Estado -->
                        <div class="hidden-xs col-sm-1 own-column text-center own-column--border own-column-estado">
                            <span class="own-column-conten">

                                {% if record.is_Complete %}
                                    <span class="glyphicon glyphicon-ok-sign own-data-icon-success" aria-hidden="true"></span>
                                {% elif record.is_Cancel %}
                                    <span class="glyphicon glyphicon-minus-sign own-data-icon-cancel" aria-hidden="true"></span>
                                {% elif record.status == 'pen' %}
                                    <span class="glyphicon glyphicon-time own-data-icon-warning" aria-hidden="true"></span>
                                {% else %}
                                    <span class="glyphicon glyphicon-adjust own-data-icon-info" aria-hidden="true"></span>
                                {% endif %}
                            </span>
                        </div>

                        <!-- Fecha Informacion -->
                        <div class="col-sx-12 col-sm-3 col-md-2 own-column own-column-range own-column--border">
                            <span class="own-data-label" >
                                Fecha Información:
                            </span>
                            <span class="glyphicon glyphicon-calendar own-data-icon" aria-hidden="true"></span>
                            <span class="own-data-normalvalue">
                                {{record.date|date:"d M Y"}}
                            </span>
                        </div>

                        <!-- Fecha Solicitud -->
                        <div class="col-sx-12 col-sm-3 col-md-2 own-column own-column--border">
                            <span class="own-data-label" >
                                Fecha Solicitud:
                            </span>
                            <span class="glyphicon glyphicon-calendar own-data-icon" aria-hidden="true"></span>
                            <span class="own-data-normalvalue">
                                {{record.created_date|naturaltime|default:"" }}
                            </span>
                        </div>

                        <!-- Comand -->
                        <a href="{% url 'labor:incident_view' record.pk %}" class="col-sx-12 col-sm-1 col-md-1 own-column own-comando">

                            <span class="glyphicon glyphicon-edit own-link-icon" aria-hidden="true"></span>
                            <span class="own-data-normalvalue own-data-comandvalue">
                                Revisar
                            </span>
                        </a>

                    </div>
                {% endfor %}

                <div class="text-center">
                    <ul class="pagination pagination-sm no-margin">
                        {% if records.has_previous %}
                            <li><a href="?{{ page_request_var }}={{ records.previous_page_number }}&q={{ request.GET.q }}">&laquo;</a></li>
                        {% endif %}

                        {% for i in records.paginator.page_range %}
                            <li {% if records.number == i %} class="active own-active" {% endif %}>
                                <a href="?page={{i}}&q={{ request.GET.q }}">{{ i }}</a>
                            </li>
                        {% endfor %}

                        {% if records.has_next %}
                            <li><a href="?page={{ records.next_page_number }}&q={{ request.GET.q }}">&raquo;</a></li>
                        {% endif %}
                    </ul>
                </div>

            {% else %}
                <h1 class="text-center">Sin solicitudes</h1>
            {% endif %}
        </div>

    </div>

{% endblock content %}