Prometeus/urls.py
# -*- coding: utf-8 -*-

# Django's Libraries
from django.conf import settings
from django.conf.urls import url
from django.conf.urls import include
from django.conf.urls.static import static

from django.contrib import admin


urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^admin/', admin.site.urls),

    url(r'', include('editorial.urls', namespace="editorial")),
    url(r'', include('home.urls', namespace="home")),
    url(r'', include('labor.urls', namespace="labor")),
    url(r'', include('management.urls', namespace="management")),
    url(r'', include('payroll.urls', namespace="payroll")),
    url(r'', include('security.urls', namespace="security")),

    url(r'api/', include('payroll.urls_rest', namespace="api-payroll")),
    url(r'api/', include('social.urls_rest', namespace="api-social")),
    url(r'api/', include('labor.urls_rest', namespace="api-labor")),
]


if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
# -*- coding: utf-8 -*-

# Django's Libraries
from django.conf.urls import url

# Own's Libraries
from .views import LandingView


urlpatterns = [
    url(r'^$', LandingView.as_view(), name="landing"),
]

payroll/urls.py
# -*- coding: utf-8 -*-

# Django's Libraries
from django.conf.urls import url

# Own's Libraries
from .views import VoucherListView
from .views import VoucherListEdit
from .views import VoucherAdd
from .views import VoucherAddSuccess
from .views import VoucherView
from .views import VoucherEdit
from .views import VoucherCancel

from .views import BenefitListView
from .views import BenefitListEdit
from .views import BenefitCancel
from .views import BenefitAdd
from .views import BenefitAddSuccess
from .views import BenefitEdit


urlpatterns = [

    # Vouchers
    url(
        r'^vouchers/pending/$',
        VoucherListView.as_view(), {'_status': 'pending'},
        name="voucher_list_pending"
    ),
    url(
        r'^vouchers/all/$',
        VoucherListView.as_view(), {'_status': 'all'},
        name="voucher_list_all"
    ),
    url(
        r'^vouchers/admin/pending/$',
        VoucherListEdit.as_view(), {'_status': 'pending'},
        name="voucher_list_admin_pending"
    ),
    url(
        r'^vouchers/admin/all/$',
        VoucherListEdit.as_view(), {'_status': 'all'},
        name="voucher_list_admin_all"
    ),
    url(
        r'^vouchers/add/$',
        VoucherAdd.as_view(),
        name="voucher_add"
    ),
    url(
        r'^vouchers/add/success/$',
        VoucherAddSuccess.as_view(),
        name="voucher_add_success"
    ),
    url(
        r'^vouchers/(?P<pk>\d+)/view/$',
        VoucherView.as_view(),
        name="voucher_view"
    ),
    url(
        r'^vouchers/(?P<pk>\d+)/edit/$',
        VoucherEdit.as_view(),
        name="voucher_edit"
    ),
    url(
        r'^vouchers/(?P<_pk>\d+)/cancel/$',
        VoucherCancel.as_view(),
        name="voucher_cancel"
    ),

    # Benefits
    url(
        r'^benefits/pending/$',
        BenefitListView.as_view(), {'_status': 'pending'},
        name="benefit_list_pending"
    ),
    url(
        r'^benefits/all/$',
        BenefitListView.as_view(), {'_status': 'all'},
        name="benefit_list_all"
    ),
    url(
        r'^benefits/admin/pending/$',
        BenefitListEdit.as_view(), {'_status': 'pending'},
        name="benefit_list_admin_pending"
    ),
    url(
        r'^benefits/admin/all/$',
        BenefitListEdit.as_view(), {'_status': 'all'},
        name="benefit_list_admin_all"
    ),
    url(
        r'^benefits/add/$',
        BenefitAdd.as_view(),
        name="benefit_add"
    ),
    url(
        r'^benefits/add/success/$',
        BenefitAddSuccess.as_view(),
        name="benefit_add_success"
    ),
    url(
        r'^benefits/(?P<pk>\d+)/edit/$',
        BenefitEdit.as_view(),
        name="benefit_edit"
    ),
    url(
        r'^benefits/(?P<pk>\d+)/cancel/$',
        BenefitCancel.as_view(),
        name="benefit_cancel"
    ),
]

payroll/models.py
# -*- coding: utf-8 -*-

# Python's Libraries
from __future__ import unicode_literals

# Django's Libraries
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

# Own's Libraries
from .utilities import Helper
from security.models import Profile
from social.business import CommentBusiness


class VoucherType(models.Model):
    name = models.CharField(
        "Nombre",
        max_length=50,
        blank=False,
        unique=True
    )
    description = models.TextField("Descripción", blank=True, null=True)
    valid_range = models.BooleanField(
        "Validar rangos de fechas",
        default=True
    )

    created_date = models.DateTimeField(
        auto_now=False,
        auto_now_add=True,
    )
    updated_date = models.DateTimeField(
        auto_now=True,
        auto_now_add=False,
    )

    class Meta:
        verbose_name = 'Tipo de Comprobante'
        verbose_name_plural = 'Tipos de Comprobantes'

    def __unicode__(self):
        return self.name


class VoucherRequisition(models.Model):
    STATUS_OPTIONS = (
        ('pen', 'PENDIENTE'),
        ('can', 'CANCELADO'),
        ('com', 'COMPLETADO'),
    )

    employee = models.ForeignKey(
        Profile,
        verbose_name="Empleado",
        blank=False,
        on_delete=models.PROTECT
    )
    type = models.ForeignKey(
        VoucherType,
        verbose_name="Tipo",
        blank=False,
        on_delete=models.PROTECT
    )
    date_start = models.DateField("Fecha Inicio", blank=True, null=True)
    date_end = models.DateField("Fecha Fin", blank=True, null=True)
    reason = models.TextField("Motivo de la Solicitud", blank=True, null=True)
    response = models.TextField(
        "Respuesta de Administracion", blank=True, null=True)
    file = models.FileField(
        "Archivo",
        upload_to=Helper.get_FilePath_Voucher,
        validators=[
            Helper.validate_Size
        ],
        blank=True,
        null=True,
    )
    status = models.CharField(
        "Estado",
        max_length=3,
        choices=STATUS_OPTIONS,
        default="pen"
    )
    created_by = models.ForeignKey(
        Profile,
        verbose_name="Creado por",
        related_name='sc_created_by',
        blank=True,
        null=True
    )
    created_date = models.DateTimeField(
        auto_now=False,
        auto_now_add=True,
    )
    updated_by = models.ForeignKey(
        Profile,
        verbose_name="Actualizado por",
        related_name='sc_updated_by',
        blank=True,
        null=True
    )
    updated_date = models.DateTimeField(
        auto_now=True,
        auto_now_add=False,
    )

    def clean(self):
        fecha_inicio = self.date_start
        fecha_fin = self.date_end
        tipo = self.type

        if tipo.valid_range:
            if fecha_inicio is None:
                raise ValidationError({
                    'date_start': _(
                        'Fecha Inicial no proporcionada.'
                    )
                })

            if fecha_fin is None:
                raise ValidationError({
                    'date_end': _(
                        'Fecha Fin no proporcionada.'
                    )
                })

            if fecha_fin < fecha_inicio:
                raise ValidationError({
                    'date_end': _(
                        'Fecha final no puede ser menor que fecha inicial.'
                    )
                })

    class Meta:
        verbose_name = 'Solicitud de Comprobante'
        verbose_name_plural = 'Solicitudes de Comprobantes'

    def __unicode__(self):
        desc = "%s : %s - %s" % (self.pk, self.employee, self.type)
        return desc

    @property
    def is_Complete(self):
        if self.status == "com":
            return True
        else:
            return False

    @property
    def is_Cancel(self):
        if self.status == "can":
            return True
        else:
            return False

    @property
    def is_Editable(self):
        if self.status == "can" or self.status == "com":
            return False
        else:
            return True

    @property
    def comments(self):
        records = CommentBusiness.get(self.__class__, self.id)
        return records


class BenefitType(models.Model):
    name = models.CharField(
        "Nombre",
        max_length=50,
        blank=False,
        unique=True
    )
    description = models.TextField("Descripción", blank=True, null=True)

    created_date = models.DateTimeField(
        auto_now=False,
        auto_now_add=True,
    )
    updated_date = models.DateTimeField(
        auto_now=True,
        auto_now_add=False,
    )

    class Meta:
        verbose_name = 'Tipo de Prestacion'
        verbose_name_plural = 'Tipos de Prestaciones'

    def __unicode__(self):
        return self.name


class BenefitRequisition(models.Model):
    STATUS = (
        ('pen', 'Pendiente'),
        ('ppe', 'Pago Pendiente'),
        ('ppc', 'Pago Por Comprobar'),
        ('com', 'Completado'),
        ('can', 'Cancelado')
    )

    employee = models.ForeignKey(
        Profile,
        verbose_name="Empleado",
        blank=False,
        on_delete=models.PROTECT
    )
    type = models.ForeignKey(
        BenefitType,
        verbose_name="Tipo",
        blank=False,
        on_delete=models.PROTECT
    )
    date = models.DateField("Fecha")
    reason = models.TextField("Motivo de la Solicitud", blank=True)
    payment_evidence = models.TextField("Evidencia del Pago", blank=True)
    admin_response = models.TextField(
        "Respuesta de Administración",
        blank=True
    )
    payment_info = models.TextField("Informacion del Pago", blank=True)
    status = models.CharField(
        "Estado", max_length=3, choices=STATUS, default="pen")
    created_by = models.ForeignKey(
        Profile,
        verbose_name="Creado por",
        related_name='sp_created_by',
        blank=True,
        null=True
    )
    created_date = models.DateTimeField(
        auto_now=False,
        auto_now_add=True,
    )
    updated_by = models.ForeignKey(
        Profile,
        verbose_name="Actualizado por",
        related_name='sp_updated_by',
        blank=True,
        null=True
    )
    updated_date = models.DateTimeField(
        auto_now=True,
        auto_now_add=False,
    )

    class Meta:
        verbose_name = 'Solicitud de Prestacion'
        verbose_name_plural = 'Solicitudes de Prestaciones'

    def __unicode__(self):
        desc = "%s : %s - %s" % (self.pk, self.employee, self.type)
        return desc

    @property
    def is_Complete(self):
        if self.status == "com":
            return True
        else:
            return False

    @property
    def is_Cancel(self):
        if self.status == "can":
            return True
        else:
            return False

    @property
    def is_Editable(self):
        if self.status == "can" or self.status == "com":
            return False
        else:
            return True

    @property
    def comments(self):
        records = CommentBusiness.get(self.__class__, self.id)
        return records

payroll/forms.py
# -*- coding: utf-8 -*-

# Django's Libraries
from django.forms import ModelForm
from django.forms import Select
# from django.forms import TextInput
from django.forms import FileInput
from django.forms import DateInput
from django.forms import Textarea
from django.forms import ValidationError

# Own's Libraries
from .models import VoucherRequisition, BenefitRequisition


class VoucherRequisitionAddForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(VoucherRequisitionAddForm, self).__init__(*args, **kwargs)
        self.fields['reason'].required = True

    class Meta:
        model = VoucherRequisition
        fields = (
            'type',
            'date_start',
            'date_end',
            'reason',
        )
        exclude = [
            'employee',
            'response',
            'is_complete',
        ]

        widgets = {
            'date_start': DateInput(
                attrs={'class': 'form-control'},
                format='%d/%m/%Y'
            ),
            'date_end': DateInput(
                attrs={'class': 'form-control'},
                format='%d/%m/%Y'
            ),
            'type': Select(attrs={'class': 'form-control'}),
            'reason': Textarea(attrs={'class': 'form-control', 'rows': '8'}),
        }

        labels = {
            'type': 'Tipo de comprobante:',
            'reason': 'Motivo:'
        }


class VoucherRequisitionEditForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(VoucherRequisitionEditForm, self).__init__(*args, **kwargs)
        instance = kwargs['instance']        
        self.fields['response'].required = True
        if instance.status == 'can' or instance.status == 'com':
            self.fields['status'].widget.attrs['readonly'] = True
            self.fields['file'].widget.attrs['readonly'] = True
            self.fields['response'].widget.attrs['readonly'] = True

    class Meta:
        model = VoucherRequisition
        fields = (
            'file',
            'status',
            'response',
        )
        exclude = [
            'employee',
            'type',
            'date_start',
            'date_end',
            'reason',
            'created_by',
            'created_date',
            'updated_by',
            'updated_date',
        ]
        widgets = {
            'file': FileInput(attrs={
                'class': 'filestyle',
                'data-iconName': 'glyphicon glyphicon-file',
                'data-buttonText': 'Seleccionar Archivo'
            }),
            'status': Select(attrs={'class': 'form-control'}),
            'response': Textarea(attrs={'class': 'form-control', 'rows': '8'}),
        }
        labels = {
            'file': 'Archivo',
            'status': 'Estado',
            'response': 'Respuesta',
        }

    def clean(self):
        status = self.cleaned_data['status']
        file = self.cleaned_data['file']
        response = self.cleaned_data['response']

        if status == "com":
            if file is None:
                raise ValidationError(
                    "No se puede marcar como Completado "
                    "sin adjuntar un archivo"
                )

            if response == "":
                raise ValidationError(
                    "Favor de dar una respuesta al Empleado"
                )

        if status == "can" and response == "":
            raise ValidationError(
                "Favor de dar explicar porque estas cancelando la solicitud"
            )


class BenefitRequisitionAddForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(BenefitRequisitionAddForm, self).__init__(*args, **kwargs)
        self.fields['reason'].required = True

    class Meta:
        model = BenefitRequisition
        fields = (
            'type',
            'date',
            'reason',
        )
        widgets = {
            'date': DateInput(
                attrs={'class': 'form-control'},
                format='%d/%m/%Y'
            ),
            'type': Select(attrs={'class': 'form-control'}),
            'reason': Textarea(attrs={'class': 'form-control', 'rows': '8'}),
        }

        labels = {
            'type': 'Tipo de Prestacion:',
            'reason': 'Motivo:'
        }


class BenefitRequisitionEditForm(ModelForm):
    user_fields = ['payment_evidence', ]  # Fill with user fillable fields.

    def __init__(self, is_admin_form=False, is_cancelled=False, *args, **kwargs):
        super(BenefitRequisitionEditForm, self).__init__(*args, **kwargs)
        self.fields['status'].required = False
        if not is_cancelled:
            if is_admin_form:
                for field in [x for x in self.fields if x in self.user_fields]:
                    self.fields[field].widget.attrs['readonly'] = True
            else:
                for field in [x for x in self.fields if not x in self.user_fields]:
                    self.fields[field].widget.attrs['readonly'] = True
        else:
            for field in self.fields:
                self.fields[field].widget.attrs['readonly'] = True

    class Meta:
        model = BenefitRequisition
        fields = [
            "payment_info",
            'status',
            'payment_evidence',
            'admin_response',
        ]
        widgets = {
            "payment_info": Textarea(attrs={'class': 'form-control', 'rows': '8'}),
            "admin_response": Textarea(attrs={'class': 'form-control', 'rows': '8'}),
            "payment_evidence": Textarea(attrs={'class': 'form-control', 'rows': '8'}),
            'status': Select(attrs={'class': 'form-control'}),
        }
        labels = {
            "payment_info": 'Información del pago',
            "payment_evidence": 'Evidencia del pago',
            "admin_response": 'Respuesta del administrador',
            'status': 'Estado de la operación',
        }

payroll/templates/voucher/list_for_review.html
{% extends 'master_in.html' %}

{% load static from staticfiles %}

{% load humanize %}

{% block title %} GCM - Comprobantes {% endblock title %}

{% block css %}

    <!-- Own's Styles -->
    <link rel="stylesheet" href="{% static 'voucher/list.min.css' %}" />

{% endblock css %}

{% block content %}

    <div class="container-fluid">
        <header>
            <h3 class="own-titulo">Comprobantes</h3>
        </header>
        <hr>
        <nav>
            <div class="row">
                <div class="col-xs-12 col-sm-6">
                    <a href="{% url 'payroll:voucher_add' %}" class="btn btn-primary ">
                        <i class="fa fa-plus-circle" aria-hidden="true"></i>
                        Solicitar
                    </a>

                    {% if request.path == '/vouchers/all/' %}
                        <a href="{% url 'payroll:voucher_list_pending' %}" class="btn btn-info ">
                            <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
                            Ver solo pendientes
                        </a>
                    {% else %}
                        <a href="{% url 'payroll:voucher_list_all' %}" class="btn btn-info ">
                            <span class="glyphicon glyphicon-th" aria-hidden="true"></span>
                            Ver todos
                        </a>
                    {% endif %}
                </div>
                <br class="hidden-sm hidden-md hidden-lg">
                <br class="hidden-sm hidden-md hidden-lg">
                <form class="col-xs-12 col-sm-6" action="" method="GET">
                    <div class="input-group">
                        <input type="text" class="form-control" name="q" placeholder="escribe texto a buscar" value="{{ request.GET.q }}">

                        <span class="input-group-btn">
                          <button type="submit" id="boton_buscar" class="btn btn-info btn-flat">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                            <span class="hidden-xs">Buscar</span>
                          </button>
                        </span>
                    </div>
                </form>
            </div>
        </nav>
        <br>
        <br class="hidden-xs">

        <div class="container-fluid">
            {% if records %}

                <div class="row own-record-titles">

                    <div class="col-sm-4 col-md-6">TIPO</div>

                    <div class="col-sm-1 col-md-1">ESTADO</div>

                    <div class="col-sm-3 col-md-2">FECHA INFORMACION</div>

                    <div class="col-sm-3 col-md-2">FECHA SOLICITUD</div>

                    <div class="col-sm-1 col-md-1"></div>
                </div>

                {% for record in records %}
                    <div class="row own-record">

                        <!-- Tipo y Estado -->
                        <div class="visible-xs col-sm-5 own-column-pk
                            {% if record.is_Complete %}
                                own-column-pk-success
                            {% elif record.is_Cancel %}
                                own-column-pk-cancel
                            {% else %}
                                own-column-pk-warning
                            {% endif %}">
                            {{record.type}} - {{record.pk}}

                            <span class="own-column-conten pull-right">
                                {% if record.is_Complete %}
                                    <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                                {% elif record.is_Cancel %}
                                    <span class="glyphicon glyphicon-minus-sign" aria-hidden="true"></span>
                                {% else %}
                                    <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
                                {% endif %}
                            </span>
                        </div>

                        <!-- Tipo y Nombre -->
                        <div class="col-sx-12 col-sm-4 col-md-6 own-column-main own-column--border">

                            <div class="row">
                                <div class="hidden-xs col-sm-12 col-md-5 own-data-second">
                                    {{record.pk}} - {{record.type}}
                                </div>
                                <div class="col-sx-12 col-sm-12 col-md-7 own-data-second">
                                    <strong>{{ record.reason|truncatechars:30 }}</strong>
                                </div>
                            </div>
                        </div>

                        <!-- Estado -->
                        <div class="hidden-xs col-sm-1 own-column text-center own-column--border own-column-estado">
                            <span class="own-column-conten">

                                {% if record.is_Complete %}
                                    <span class="glyphicon glyphicon-ok-sign own-data-icon-success" aria-hidden="true"></span>
                                {% elif record.is_Cancel %}
                                    <span class="glyphicon glyphicon-minus-sign own-data-icon-cancel" aria-hidden="true"></span>
                                {% else %}
                                    <span class="glyphicon glyphicon-time own-data-icon-warning" aria-hidden="true"></span>
                                {% endif %}
                            </span>
                        </div>

                        <!-- Fecha Informacion -->
                        <div class="col-sx-12 col-sm-3 col-md-2 own-column own-column-range own-column--border">
                            <span class="own-data-label" >
                                Fecha Información:
                            </span>
                            <span class="glyphicon glyphicon-calendar own-data-icon" aria-hidden="true"></span>
                            <span class="own-data-normalvalue">
                                {{record.date_start|date:"d M Y"}} - {{record.date_end|date:"d M Y"}}
                            </span>
                        </div>

                        <!-- Fecha Solicitud -->
                        <div class="col-sx-12 col-sm-3 col-md-2 own-column own-column--border">
                            <span class="own-data-label" >
                                Fecha Solicitud:
                            </span>
                            <span class="glyphicon glyphicon-calendar own-data-icon" aria-hidden="true"></span>
                            <span class="own-data-normalvalue">
                                {{record.created_date|naturaltime|default:"" }}
                            </span>
                        </div>

                        <!-- Comand -->
                        <a href="{% url 'payroll:voucher_view' record.pk %}" class="col-sx-12 col-sm-1 col-md-1 own-column own-comando">

                            <span class="glyphicon glyphicon-edit own-link-icon" aria-hidden="true"></span>
                            <span class="own-data-normalvalue own-data-comandvalue">
                                Revisar
                            </span>
                        </a>

                    </div>
                {% endfor %}

                <div class="text-center">
                    <ul class="pagination pagination-sm no-margin">
                        {% if records.has_previous %}
                            <li><a href="?{{ page_request_var }}={{ records.previous_page_number }}&q={{ request.GET.q }}">&laquo;</a></li>
                        {% endif %}

                        {% for i in records.paginator.page_range %}
                            <li {% if records.number == i %} class="active own-active" {% endif %}>
                                <a href="?page={{i}}&q={{ request.GET.q }}">{{ i }}</a>
                            </li>
                        {% endfor %}

                        {% if records.has_next %}
                            <li><a href="?page={{ records.next_page_number }}&q={{ request.GET.q }}">&raquo;</a></li>
                        {% endif %}
                    </ul>
                </div>

            {% else %}
                <h1 class="text-center">Sin solicitudes</h1>
            {% endif %}
        </div>

    </div>

{% endblock content %}

payroll/templates/voucher/view.html
{% extends 'master_in.html' %}
{% load static from staticfiles %}
{% load social %}
{% load models %}
{% block css %}

	<!-- Alertify -->
	<link rel="stylesheet" type="text/css" href="{% static 'libs/alertifyjs/1.11.0/css/alertify.min.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'libs/alertifyjs/1.11.0/css/themes/bootstrap.min.css' %}"/>

	<!-- Own's Styles -->
	<link rel="stylesheet" type="text/css" href="{% static 'details.min.css' %}"/>

{% endblock css %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-xs-12">
            <header>
                <h3 class="own-titulo">
					<ol class="breadcrumb own-breadcrumb">
					  	<li class="own-breadcrumb-init"><a href="{% url 'payroll:voucher_list_all' %}">Solicitudes</a></li>
						<li>Solicitud de Comprobante: <span class="badge own-badge" id="object_id" data-tag-model="{{ record | get_class_name }}">{{record.pk}}</span></li>
					</ol>
				</h3>
            </header>
            <hr>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-12 col-md-8 col-lg-9">
			<div class="well">

				<div class="form-group">
					<label for="empleados">Empleado:</label>
					<input type="text" class="form-control" value="{{ record.employee }}" disabled>
				</div>

				{% if record.type.valid_range %}
					<div class="form-group">
						<label for="empleados">Fechas:</label>
						<input type="text" class="form-control" value="{{ record.date_start|date:"d M Y" }} al {{ record.date_end|date:"d M Y" }}" disabled />
					</div>
				{% endif %}

				<div class="form-group">
					<label for="empleados">Tipo de Comprobante:</label>
					<input type="text" class="form-control" value="{{ record.type }}" disabled>
				</div>

				<div class="form-group">
                    <label for="comment">Motivo de la solicitud:</label>
                    <textarea class="form-control" rows="5" disabled>{{ record.reason }}</textarea>
                </div>

				{% if record.is_Complete %}
	                <div class="form-group">
	                    <label for="comment">Respuesta de la Administracion:</label>
	                    <textarea class="form-control" rows="5" disabled>{{ record.response }}</textarea>
	                </div>

					{% if record.file %}
					<div class="form-group">
						<label for="empleados">Archivo:</label>
						<a href="{{record.file.url}}">{{record.file.name}}</a>
					</div>
					{% endif %}
				{% elif record.is_Cancel is False %}
					<div>
						<a href="{% url 'payroll:voucher_cancel' record.pk %}" class="btn btn-danger">
							Cancelar
						</a>
	                    <!--
						<button class="btn btn-primary">
							<span class="glyphicon glyphicon-print" aria-hidden="true"></span>
	                    	Imprimir
	                    </button>
						-->
	                </div>
				{% endif %}
			</div>
		</div>

        <div class="col-xs-12 col-md-4 col-lg-3">
			<div class="panel panel-default affix-top">
				<div class="panel-heading">
					<h5 class="panel-title own-panel-title">Informacion:</h5>
				</div>
				<table class="table own-table">
					<tr>
						<td class="own-table-label">
							<span class="glyphicon glyphicon-asterisk own-data-icon" aria-hidden="true"></span>
							 Estado:
						</td>
						<td class="own-table-info">
							{% if record.is_Complete %}
								<span class="label label-success own-label">
									<span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
									{{ record.get_status_display }}
								</span>
							{% elif record.is_Cancel %}
								<span class="label label-danger own-label">
									<span class="glyphicon glyphicon-minus-sign" aria-hidden="true"></span>
									{{ record.get_status_display }}
								</span>
							{% else %}
								<span class="label label-warning own-label">
									<span class="glyphicon glyphicon-time" aria-hidden="true"></span>
									{{ record.get_status_display }}
								</span>
							{% endif %}
						</td>
					</tr>
					<tr>
						<td class="own-table-label">
							<span class="glyphicon glyphicon-user own-data-icon" aria-hidden="true"></span>
							Creado por:
						</td>
						<td class="own-table-info">{{ record.created_by|default:"" }}</td>
					</tr>
					<tr>
						<td class="own-table-label">
							<span class="glyphicon glyphicon-calendar own-data-icon" aria-hidden="true"></span>
							Creado el:
						</td>
						<td class="own-table-info">{{ record.created_date|date:"d M Y" }}</td>
					</tr>
					<tr>
						<td class="own-table-label">
							<span class="glyphicon glyphicon-user own-data-icon" aria-hidden="true"></span>
							Actualizado por:
						</td>
						<td class="own-table-info">{{ record.updated_by|default:"" }}</td>
					</tr>
					<tr>
						<td class="own-table-label">
							<span class="glyphicon glyphicon-calendar own-data-icon" aria-hidden="true"></span>
							Actualizado el:
						</td>
						<td class="own-table-info">{{ record.updated_date|date:"d M Y" }}</td>
					</tr>
				</table>
			</div>
        </div>
	</div>

	{% tag_comments record %}
</div>

{% endblock content %}

{% block scripts %}

	<!-- JS Cookie -->
	<script src="{% static 'libs/js-cookie/2.2.0/src/js.cookie.js' %}"></script>

	<!-- Alertify -->
	<script src="{% static 'libs/alertifyjs/1.11.0/alertify.min.js' %}"></script>
	<script src="{% static 'alerts.min.js' %}"></script>

	<!-- Mommentjs -->
	<script src="{% static 'libs/momentjs/2.19.3/moment-with-locales.min.js' %}"></script>

	<!-- Own's Libraries -->
	<script src="{% static 'comment.min.js' %}"></script>

{% endblock scripts %}